//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignUpDemo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SinhVienEntities1 : DbContext
    {
        public SinhVienEntities1()
            : base("name=SinhVienEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_DangNhap> tbl_DangNhap { get; set; }
        public virtual DbSet<tbl_Diem> tbl_Diem { get; set; }
        public virtual DbSet<tbl_DMMonHoc> tbl_DMMonHoc { get; set; }
        public virtual DbSet<tbl_Khoa> tbl_Khoa { get; set; }
        public virtual DbSet<tbl_SinhVien> tbl_SinhVien { get; set; }
    }
}
